from typing import Protocol

from attack2patch.types.deployment import Deployment


class DeploymentRepository(Protocol):
    def save(self, deployment: Deployment) -> None: ...

    def get_deployment(self, deployment_id: str) -> Deployment | None: ...

    def deployments_for_patch(self, patch_id: str) -> list[Deployment]: ...

    def latest_completed_deployment(self) -> Deployment | None: ...
