from typing import Protocol

from attack2patch.types.attack_event import AttackEvent
from attack2patch.types.finding import CodeFinding
from attack2patch.types.patch import PatchCandidate


class EventRepository(Protocol):
    def save(self, event: AttackEvent) -> None: ...

    def get(self, event_id: str) -> AttackEvent | None: ...

    def list_events(self) -> list[AttackEvent]: ...

    def save_finding(self, finding: CodeFinding) -> None: ...

    def get_finding(self, finding_id: str) -> CodeFinding | None: ...

    def findings_for_event(self, event_id: str) -> list[CodeFinding]: ...

    def save_patch(self, patch: PatchCandidate) -> None: ...

    def get_patch(self, patch_id: str) -> PatchCandidate | None: ...

    def patches_for_event(self, event_id: str) -> list[PatchCandidate]: ...
